### ISSUE TITLE
Absent fields from ULT and UST

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-content-validation#28] opened 2020-09-10 14:53 UTC
Sometimes the UST has them as in the picture attached.

![image](https://user-images.githubusercontent.com/1289437/92748744-72ad0c00-f353-11ea-8307-47273a76553b.png)

However, sometimes they are absent from UST as well:
![image](https://user-images.githubusercontent.com/1289437/92749102-c9b2e100-f353-11ea-8bc3-83825a030b4f.png)

**Comment by RobH123** [comment] 2020-09-23 20:05
This appears to be a duplicate of #27 ? Anyway the same answer applies:

Yes, some methods of detecting errors don't provide all the information @mandolyte -- the only guaranteed notice fields are priority and message. Everything else may be omitted if it's irrelevant or unknown.

**Closed by RobH123** 2020-09-23 20:05 UTC
